apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service
  namespace: fintech-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
    spec:
      containers:
      - name: core-service
        image: 982081054052.dkr.ecr.ap-south-1.amazonaws.com/fintech/banking-core:v1
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-host
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-password
        command: ["/bin/sh","-c"]
        args:
          - java -jar app.jar --spring.datasource.url=jdbc:mysql://$(DB_HOST)/banking_core_db


apiVersion: v1
kind: Service
metadata:
  name: internet-banking-core-service
  namespace: fintech-prod
spec:
  selector:
    app: core-service
  ports:
  - port: 80
    targetPort: 8080