apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service
  namespace: fintech-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
    spec:
      containers:
      - name: core-service
        image: 982081054052.dkr.ecr.ap-south-1.amazonaws.com/fintech/banking-core:0180d1403f5994e7b1cdedf96d7e4d78b3e4491b
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-host
              optional: false
        - name: SPRING_DATASOURCE_URL_FULL
          value: "jdbc:mysql://$(SPRING_DATASOURCE_URL)/banking_core_db"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-password
        
        # FIXED INDENTATION HERE:
        command: ["/bin/sh", "-c"]
        args: ["java -jar app.jar --spring.datasource.url=jdbc:mysql://$(SPRING_DATASOURCE_URL)/banking_core_db"]

# FIXED SEPARATOR HERE (No spaces before ---)
---
apiVersion: v1
kind: Service
metadata:
  name: internet-banking-core-service
  namespace: fintech-prod
spec:
  selector:
    app: core-service
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080