apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials-syncer
  namespace: fintech-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
  - secretKey: db-host
    remoteRef:
      key: fintech/prod/db-credentials
      property: db-host
  - secretKey: db-username
    remoteRef:
      key: fintech/prod/db-credentials
      property: db-username
  - secretKey: db-password
    remoteRef:
      key: fintech/prod/db-credentials
      property: db-password
