apiVersion: apps/v1
kind: Deployment
metadata:
  name: fund-transfer
  namespace: fintech-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fund-transfer
  template:
    metadata:
      labels:
        app: fund-transfer
    spec:
      containers:
      - name: fund-transfer
        image: 982081054052.dkr.ecr.ap-south-1.amazonaws.com/fintech/fund-transfer:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-password
        - name: BANKING_CORE_URL
          value: "http://internet-banking-core-service:8080"
        - name: SPRING_JPA_HIBERNATE_DDL-AUTO
          value: "update"
        - name: SPRINGDOC_SWAGGER_UI_CONFIG_URL
          value: "/api/v1/transaction/v3/api-docs/swagger-config"
        - name: KEYCLOAK_AUTH_SERVER_URL
          value: "http://3.109.163.253.nip.io"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-host
        command: ["/bin/sh", "-c"]
        args: ["java -jar app.jar --spring.datasource.url=jdbc:mysql://$(DB_HOST)/banking_user_db"]
---
apiVersion: v1
kind: Service
metadata:
  name: fund-transfer
  namespace: fintech-prod
spec:
  selector:
    app: fund-transfer
  type: ClusterIP 
  ports:
    - port: 80
      targetPort: 8080