apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: fintech-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:24.0.1
        args: ["start-dev"]
        ports:
        - containerPort: 8080
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"

        # --- NETWORK CONFIG ---
        - name: KC_PROXY
          value: "edge"
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "false"

        # --- THE FIXES ---
        
        # 1. Hostname MUST include the port if you see it in the browser
        - name: KC_HOSTNAME
          value: "a16df262c5cae44318644bdae3897f7a-720103841.ap-south-1.elb.amazonaws.com"
        - name: KC_HOSTNAME_PORT
          value: "8080"
          
        # 2. Disable SSL Cookies (Fixes "Cookie not found")
        - name: KC_SPI_SSL_REQUIRED
          value: "none"

        # 3. FIX THE IFRAME TIMEOUT (The magic variable)
        - name: KC_SPI_STICKY_SESSION_ENCODER_INFI_SPAN_SHOULD_ATTACH_AUTH_SESSION_ID
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: fintech-prod
spec:
  selector:
    app: keycloak
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080