apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: fintech-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:24.0.1
        args: ["start-dev"]
        ports:
        - containerPort: 8080
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"

        # --- 🚨 THE ALTERNATIVE FIX: TRUST EVERYTHING 🚨 ---

        # 1. Trust the Load Balancer Headers (Crucial)
        - name: KC_PROXY
          value: "edge"
          
        # 2. Disable Hostname Verification (Stop checking the URL)
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "false"
          
        # 3. Enable HTTP
        - name: KC_HTTP_ENABLED
          value: "true"

        # 4. Disable Secure Cookies (Fixes "Cookie not found")
        - name: KC_SPI_SSL_REQUIRED
          value: "none"
          
        # 5. Fix Iframe Timeout (Fixes the spinner)
        - name: KC_SPI_STICKY_SESSION_ENCODER_INFI_SPAN_SHOULD_ATTACH_AUTH_SESSION_ID
          value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: fintech-prod
spec:
  selector:
    app: keycloak
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080