apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: fintech-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:24.0.1
        args: ["start-dev"]
        ports:
        - containerPort: 8080
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"

        # --- 🚨 NUCLEAR FIX CONFIGURATION 🚨 ---
        
        # 1. FORCE THE PUBLIC URL (Frontend & Redirects)
        # We explicitly tell Keycloak: "This is your URL. Do not guess."
        - name: KC_HOSTNAME_URL
          value: "http://a16df262c5cae44318644bdae3897f7a-720103841.ap-south-1.elb.amazonaws.com:8080"
        
        # 2. FORCE THE ADMIN CONSOLE URL (Backend UI)
        # This fixes the "Loading..." spinner and mixed content errors
        - name: KC_HOSTNAME_ADMIN_URL
          value: "http://a16df262c5cae44318644bdae3897f7a-720103841.ap-south-1.elb.amazonaws.com:8080"

        # 3. NETWORK PROXY SETTINGS
        - name: KC_PROXY
          value: "edge"  # Trust AWS ELB headers
        - name: KC_HTTP_ENABLED
          value: "true"
        
        # 4. DISABLE SECURITY CHECKS (Dev Mode)
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "false"
        
        # 5. DISABLE SSL COOKIES (Fixes "Cookie not found")
        - name: KC_SPI_SSL_REQUIRED
          value: "none"
          
        # 6. FIX IFRAME TIMEOUT
        - name: KC_SPI_STICKY_SESSION_ENCODER_INFI_SPAN_SHOULD_ATTACH_AUTH_SESSION_ID
          value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: fintech-prod
spec:
  selector:
    app: keycloak
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080