apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: fintech-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: 982081054052.dkr.ecr.ap-south-1.amazonaws.com/fintech/user-service:96f00aab0cd399573aed74df8b3c61a09e622202
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-password
        # Connection to Core Service (Using K8s DNS name)
        - name: BANKING_CORE_URL
          value: "http://internet-banking-core-service:8080"
        # Database Connection
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-host
        command: ["/bin/sh", "-c"]
        args: ["java -jar app.jar --spring.datasource.url=jdbc:mysql://$(DB_HOST)/banking_user_db"]
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: fintech-prod
spec:
  selector:
    app: user-service
  type: LoadBalancer # Public Access for Swagger/Frontend
  ports:
    - port: 80
      targetPort: 8080