apiVersion: apps/v1
kind: Deployment
metadata:
  name: utility-service
  namespace: fintech-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: utility-service
  template:
    metadata:
      labels:
        app: utility-service
    spec:
      containers:
      - name: utility-service
        image: 982081054052.dkr.ecr.ap-south-1.amazonaws.com/fintech/utility-service:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-password
        - name: BANKING_CORE_URL
          value: "http://internet-banking-core-service:8080"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-host
        command: ["/bin/sh", "-c"]
        args: ["java -jar app.jar --spring.datasource.url=jdbc:mysql://$(DB_HOST)/banking_user_db"]
---
apiVersion: v1
kind: Service
metadata:
  name: utility-service
  namespace: fintech-prod
spec:
  selector:
    app: utility-service
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080